<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\NotificationRule;
use App\Models\Stock;
use App\Models\User;
use App\Services\MarketData\MarketDataIngestor;
use App\Services\MarketData\SyntheticMarketDataProvider;
use App\Services\News\NewsIngestor;
use App\Services\News\NewsMatcherService;
use App\Services\News\SentimentAnalyzer;
use App\Services\News\SyntheticNewsProvider;
use Illuminate\Database\Seeder;

/**
 * Seeds runnable demo content: prices for every stock, a stream of matched +
 * scored news, and demo/admin accounts with a watchlist and an alert rule.
 *
 * Everything is generated by the synthetic providers, so no API keys are needed.
 */
class DemoContentSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('Generating prices…');
        $this->seedPrices();

        $this->command->info('Generating + matching news…');
        $this->seedNews();

        $this->command->info('Creating demo accounts…');
        $this->seedUsers();
    }

    private function seedPrices(): void
    {
        $ingestor = new MarketDataIngestor(new SyntheticMarketDataProvider);

        Stock::query()->active()->get()->each(fn (Stock $stock) => $ingestor->sync($stock));
    }

    private function seedNews(): void
    {
        $ingestor = new NewsIngestor(new SyntheticNewsProvider);
        $analyzer = new SentimentAnalyzer;
        $matcher = new NewsMatcherService;

        // A few rounds to build up a feed (the ingestor dedupes + assigns a source).
        for ($round = 0; $round < 4; $round++) {
            foreach ($ingestor->ingest(null, 20) as $item) {
                $analyzer->applyTo($item);
                $matcher->match($item);
            }
        }
    }

    private function seedUsers(): void
    {
        User::factory()->admin()->create([
            'name' => 'Admin',
            'email' => 'admin@tradenews.test',
        ]);

        $demo = User::factory()->create([
            'name' => 'Demo User',
            'email' => 'demo@tradenews.test',
        ]);

        // Watchlist: a handful of stocks across both markets.
        Stock::query()
            ->whereIn('symbol', ['THYAO', 'ASELS', 'AAPL', 'NVDA', 'TSLA'])
            ->get()
            ->values()
            ->each(fn (Stock $stock, int $i) => $demo->watchlist()->create([
                'stock_id' => $stock->id,
                'alerts_enabled' => true,
                'position' => $i,
            ]));

        NotificationRule::factory()->create([
            'user_id' => $demo->id,
            'name' => 'Watchlist alerts',
            'interval_minutes' => 15,
            'only_watchlist' => true,
            'min_importance' => 0,
            'is_active' => true,
        ]);

        // Start the Telegram link flow unconnected so it can be demoed end-to-end.
        $demo->telegramIntegration()->create(['is_enabled' => false]);
    }
}
